# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "rake", "~> 12.0"
gem "rspec", "~> 3.0"
gem "asciidoctor", "~> 2.0.10"
gem "asciidoctor-pdf", "~> 1.5.3"
gem "prawn", "~> 2.2.2"
gem "prawn-table", "~> 0.2.2"
gem 'asciidoctor-nabetani'
gem 'asciidoctor-pdf-cjk-kai_gen_gothic'
